# This file is generated by https://github.com/adoyle-h/shell-colors
# Author: ADoyle <adoyle.h@gmail.com>
# License: BSD 3-clause License

# General Foreground Colors
__prompt_BLACK='\e[30m'
__prompt_RED='\e[31m'
__prompt_GREEN='\e[32m'
__prompt_YELLOW='\e[33m'
__prompt_BLUE='\e[34m'
__prompt_PURPLE='\e[35m'
__prompt_CYAN='\e[36m'
__prompt_WHITE='\e[37m'
__prompt_GREY='\e[90m'

# General Background Colors
__prompt_BG_BLACK='\e[30;40m'
__prompt_BG_RED='\e[31;41m'
__prompt_BG_GREEN='\e[32;42m'
__prompt_BG_YELLOW='\e[33;43m'
__prompt_BG_BLUE='\e[34;44m'
__prompt_BG_PURPLE='\e[35;45m'
__prompt_BG_CYAN='\e[36;46m'
__prompt_BG_WHITE='\e[37;47m'
__prompt_BG_GREY='\e[100m'

# BOLD
__prompt_BOLD_BLACK='\e[30;1m'
__prompt_BOLD_RED='\e[31;1m'
__prompt_BOLD_GREEN='\e[32;1m'
__prompt_BOLD_YELLOW='\e[33;1m'
__prompt_BOLD_BLUE='\e[34;1m'
__prompt_BOLD_PURPLE='\e[35;1m'
__prompt_BOLD_CYAN='\e[36;1m'
__prompt_BOLD_WHITE='\e[37;1m'
__prompt_BOLD_GREY='\e[1;90m'

# UNDERLINE
__prompt_UL_BLACK='\e[30;4m'
__prompt_UL_RED='\e[31;4m'
__prompt_UL_GREEN='\e[32;4m'
__prompt_UL_YELLOW='\e[33;4m'
__prompt_UL_BLUE='\e[34;4m'
__prompt_UL_PURPLE='\e[35;4m'
__prompt_UL_CYAN='\e[36;4m'
__prompt_UL_WHITE='\e[37;4m'
__prompt_UL_GREY='\e[4;90m'

# BLINK
__prompt_BLK_BLACK='\e[30;5m'
__prompt_BLK_RED='\e[31;5m'
__prompt_BLK_GREEN='\e[32;5m'
__prompt_BLK_YELLOW='\e[33;5m'
__prompt_BLK_BLUE='\e[34;5m'
__prompt_BLK_PURPLE='\e[35;5m'
__prompt_BLK_CYAN='\e[36;5m'
__prompt_BLK_WHITE='\e[37;5m'
__prompt_BLK_GREY='\e[5;90m'

# REVERSE
__prompt_REV_BLACK='\e[30;7m'
__prompt_REV_RED='\e[31;7m'
__prompt_REV_GREEN='\e[32;7m'
__prompt_REV_YELLOW='\e[33;7m'
__prompt_REV_BLUE='\e[34;7m'
__prompt_REV_PURPLE='\e[35;7m'
__prompt_REV_CYAN='\e[36;7m'
__prompt_REV_WHITE='\e[37;7m'
__prompt_REV_GREY='\e[7;90m'

# BRIGHT
__prompt_BRI_BLACK='\e[90m'
__prompt_BRI_RED='\e[91m'
__prompt_BRI_GREEN='\e[92m'
__prompt_BRI_YELLOW='\e[93m'
__prompt_BRI_BLUE='\e[94m'
__prompt_BRI_PURPLE='\e[95m'
__prompt_BRI_CYAN='\e[96m'
__prompt_BRI_WHITE='\e[97m'

# BRIGHT & BOLD
__prompt_BRI_BOLD_BLACK='\e[90;1m'
__prompt_BRI_BOLD_RED='\e[91;1m'
__prompt_BRI_BOLD_GREEN='\e[92;1m'
__prompt_BRI_BOLD_YELLOW='\e[93;1m'
__prompt_BRI_BOLD_BLUE='\e[94;1m'
__prompt_BRI_BOLD_PURPLE='\e[95;1m'
__prompt_BRI_BOLD_CYAN='\e[96;1m'
__prompt_BRI_BOLD_WHITE='\e[97;1m'

# RESET
__prompt_RESET_FG='\e[39m'
__prompt_RESET_BG='\e[49m'
__prompt_RESET_ALL='\e[0m'
